apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ping-kafka-cluster
  namespace: kafka-system
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.7.0
    config:
      offsets.topic.replication.factor: 1 # TODO: Change to 3 after development
      transaction.state.log.replication.factor: 1 # TODO: Change to 3 after development
      transaction.state.log.min.isr: 1 # TODO: Change to 2 after development
      default.replication.factor: 1 # TODO: Change to 3 after development
      min.insync.replicas: 1 # TODO: Change to 2 after development
      metadata.version: "3.7"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: ping-kafka-cluster-pool
  namespace: kafka-system
  labels:
    strimzi.io/cluster: ping-kafka-cluster
spec:
  replicas: 1 # TODO: Change to 3 after development
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
