apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ping-kafka-cluster
  namespace: kafka-system
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.7.0
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
      metadata.version: "3.7"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: ping-kafka-cluster-pool
  namespace: kafka-system
  labels:
    strimzi.io/cluster: ping-kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
