apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ping-events
  namespace: kafka-system
  labels:
    strimzi.io/cluster: ping-kafka-cluster
spec:
  partitions: 1 # TODO: Change to 3 after development
  replicas: 1 # TODO: Change to 3 after development
  config:
    retention.ms: 86400000  # 24 hours
    cleanup.policy: delete
    min.insync.replicas: 1 # TODO: Change to 2 after development
