apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"flink.apache.org/v1beta1","kind":"FlinkDeployment","metadata":{"annotations":{},"name":"ping-processor","namespace":"default"},"spec":{"flinkConfiguration":{"execution.checkpointing.interval":"10s","execution.checkpointing.mode":"EXACTLY_ONCE","metrics.reporter.prometheus.class":"org.apache.flink.metrics.prometheus.PrometheusReporter","metrics.reporter.prometheus.port":"9249","metrics.reporters":"prometheus","taskmanager.numberOfTaskSlots":"2"},"flinkVersion":"v1_17","image":"ping-processor","job":{"entryClass":"com.ping.PingStreamProcessor","jarURI":"local:///opt/flink/usrlib/ping-processor-1.0-SNAPSHOT.jar","parallelism":2,"upgradeMode":"stateless"},"jobManager":{"replicas":1,"resource":{"cpu":1,"memory":"2048Mi"}},"serviceAccount":"flink","taskManager":{"resource":{"cpu":1,"memory":"2048Mi"}}}}
  creationTimestamp: "2024-10-27T03:42:40Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2024-10-27T03:47:18Z"
  finalizers:
  - flinkdeployments.flink.apache.org/finalizer
  generation: 4
  name: ping-processor
  namespace: default
  resourceVersion: "7868"
  uid: 339255f5-cb58-473b-91bb-7bbafa9dc295
spec:
  flinkConfiguration:
    execution.checkpointing.interval: 10s
    execution.checkpointing.mode: EXACTLY_ONCE
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: "9249"
    metrics.reporters: prometheus
    taskmanager.numberOfTaskSlots: "2"
  flinkVersion: v1_17
  image: ping-processor
  job:
    args: []
    entryClass: com.ping.PingStreamProcessor
    jarURI: local:///opt/flink/usrlib/ping-processor-1.0-SNAPSHOT.jar
    parallelism: 2
    state: running
    upgradeMode: stateless
  jobManager:
    replicas: 1
    resource:
      cpu: 1
      memory: 2048Mi
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 2048Mi
status:
  clusterInfo: {}
  jobManagerDeploymentStatus: DEPLOYING
  jobStatus:
    checkpointInfo:
      lastPeriodicCheckpointTimestamp: 0
    jobId: b0df8a264406e2015a08932aa29b4563
    savepointInfo:
      lastPeriodicSavepointTimestamp: 0
      savepointHistory: []
    state: RECONCILING
  lifecycleState: DEPLOYED
  observedGeneration: 3
  reconciliationStatus:
    lastReconciledSpec: '{"spec":{"job":{"jarURI":"local:///opt/flink/usrlib/ping-processor-1.0-SNAPSHOT.jar","parallelism":2,"entryClass":"com.ping.PingStreamProcessor","args":[],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"checkpointTriggerNonce":null,"upgradeMode":"stateless","allowNonRestoredState":null,"savepointRedeployNonce":null},"restartNonce":null,"flinkConfiguration":{"execution.checkpointing.interval":"10s","execution.checkpointing.mode":"EXACTLY_ONCE","metrics.reporter.prometheus.class":"org.apache.flink.metrics.prometheus.PrometheusReporter","metrics.reporter.prometheus.port":"9249","metrics.reporters":"prometheus","taskmanager.numberOfTaskSlots":"2"},"image":"ping-processor","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_17","ingress":null,"podTemplate":null,"jobManager":{"resource":{"cpu":1.0,"memory":"2048Mi","ephemeralStorage":null},"replicas":1,"podTemplate":null},"taskManager":{"resource":{"cpu":1.0,"memory":"2048Mi","ephemeralStorage":null},"replicas":null,"podTemplate":null},"logConfiguration":null,"mode":null},"resource_metadata":{"apiVersion":"flink.apache.org/v1beta1","metadata":{"generation":3},"firstDeployment":false}}'
    reconciliationTimestamp: 1730000687749
    state: DEPLOYED
  taskManager:
    labelSelector: component=taskmanager,app=ping-processor
    replicas: 1
