apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-application

# Default configuration
requires:
  - configs: 
    - ping-db-config
    path: db/skaffold.yaml
  - configs:
    - server
    path: server/skaffold.yaml

profiles:
  - name: bootstrap
    patches:
      - op: replace
        path: /requires/0/configs
        value: 
          - ping-db-install