apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-application

requires:
  - configs:
    - flink-config
    path: flink/skaffold.yaml
  - configs:
    - kafka-config
    path: kafka/skaffold.yaml
  - configs: 
    - ping-db-config
    path: postgres/skaffold.yaml
  - configs:
    - server
    path: server/skaffold.yaml

profiles:
  - name: bootstrap
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - flink-operator-install
            path: flink/skaffold.yaml
          - configs:
            - ping-db-install
            path: postgres/skaffold.yaml
          - configs:
            - kafka-install
            path: kafka/skaffold.yaml
