apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: ping-server
      context: server
      docker:
        dockerfile: server/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - server/server.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: ping-server
    port: 8080
    localPort: 8080
