apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-application

# Default configuration
requires:
  - configs:
    - kafka-config
    path: kafka/skaffold.yaml
  - configs: 
    - ping-db-config
    path: db/skaffold.yaml
  - configs:
    - server
    path: server/skaffold.yaml
  - configs:
    - flink-config
    path: flink/skaffold.yaml

profiles:
  - name: bootstrap
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
              - flink-operator-install
            path: flink/bootstrap/skaffold.yaml
          - configs:
            - ping-db-install
            path: db/skaffold.yaml
          - configs:
            - kafka-install
            path: kafka/skaffold.yaml
