apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-application
requires:
  # - configs:
  #     - server
  #   path: server/skaffold.yaml
  - configs:
      - db
    path: db/skaffold.yaml
deploy:
  tolerateFailuresUntilDeadline: true