apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-application

# Default configuration
requires:
  - configs:
    - kafka-config
    path: kafka/skaffold.yaml
  - configs: 
    - ping-db-config
    path: db/skaffold.yaml
  - configs:
    - server
    path: server/skaffold.yaml
  - configs:
    - flink-config
    path: flink/skaffold.yaml

profiles:
  - name: bootstrap
    patches:
      - op: replace
        path: /requires
        value:
          - configs:
            - ping-db-install
            path: db/skaffold.yaml
          - configs:
            - kafka-install
            path: kafka/skaffold.yaml
    deploy:
      helm:
        releases:
          - name: flink-kubernetes-operator
            repo: https://downloads.apache.org/flink/flink-kubernetes-operator-1.6.0/
            remoteChart: flink-kubernetes-operator
            namespace: flink-operator
            createNamespace: true
            wait: true
            valuesFiles:
              - flink/helm-values.yaml
