apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-processor
  template:
    metadata:
      labels:
        app: ping-processor
    spec:
      containers:
      - name: processor
        image: ping-processor
        args: ["standalone-job", "--job-classname", "com.ping.PingStreamProcessor"]
        env:
        - name: KAFKA_BROKERS
          value: "ping-kafka-cluster-kafka-bootstrap.kafka-system:9092"
