apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ping-processor
spec:
  image: ping-processor
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    
    # Checkpointing configuration for exactly-once processing
    execution.checkpointing.interval: "10s"
    execution.checkpointing.mode: EXACTLY_ONCE
    
    # Metrics
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: "9249"
    
  serviceAccount: flink
  
  jobManager:
    replicas: 1
    resource:
      memory: "2048Mi"
      cpu: 1
    resource:
      memory: "2048Mi"
      cpu: 1
    
  taskManager:
    resource:
      memory: "2048Mi"
      cpu: 1
      
  job:
    jarURI: local:///opt/flink/usrlib/ping-processor-1.0-SNAPSHOT.jar
    parallelism: 2
    upgradeMode: stateless
    entryClass: com.ping.PingStreamProcessor
