apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ping-processor
spec:
  image: ping-processor
  flinkVersion: v1_17
  flinkConfiguration:
    # High Availability
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: file:///flink-ha
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: "10 s"
    
    # Metrics & Monitoring
    metrics.reporters: prom
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.port: "9249"
    
    # Checkpointing & State
    state.backend: rocksdb
    state.backend.incremental: "true"
    state.checkpoints.dir: file:///flink-checkpoints
    execution.checkpointing.interval: 60000
    execution.checkpointing.mode: EXACTLY_ONCE
    
    # Task Configuration
    taskmanager.numberOfTaskSlots: "2"
    
  serviceAccount: flink
  podTemplate:
    spec:
      volumes:
        - name: flink-ha
          emptyDir: {}
        - name: flink-checkpoints
          emptyDir: {}
  
  jobManager:
    replicas: 2  # HA mode requires multiple JMs
    resource:
      memory: "1024m"
      cpu: 0.5
    
  taskManager:
    resource:
      memory: "1024m" 
      cpu: 0.5
      
  job:
    jarURI: local:///opt/flink/usrlib/ping-processor.jar
    parallelism: 2
    upgradeMode: savepoint
    savepointTriggerNonce: 0  # Increment to trigger savepoint
    initialSavepointPath: ""  # Set this when restoring from savepoint
    entryClass: com.ping.PingStreamProcessor
