apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ping-processor
spec:
  image: ping-processor
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: "file:///opt/flink/checkpoints"
    state.savepoints.dir: "file:///opt/flink/savepoints"
    
  serviceAccount: flink
  
  jobManager:
    replicas: 1
    resource:
      memory: "2048"
      cpu: 1
    
  taskManager:
    resource:
      memory: "2048"
      cpu: 1
      
  job:
    jarURI: local:///opt/flink/usrlib/ping-processor.jar
    parallelism: 2
    upgradeMode: savepoint
    entryClass: com.ping.PingStreamProcessor
