apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ping-processor
spec:
  image: ping-processor
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    
    # Checkpointing configuration
    execution.checkpointing.interval: "10s"
    execution.checkpointing.mode: EXACTLY_ONCE
    state.checkpoints.dir: "file:///opt/flink/data/checkpoints"
    state.savepoints.dir: "file:///opt/flink/data/savepoints"
    
    # Kafka configuration
    execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
    execution.checkpointing.min-pause: "5s"
    execution.checkpointing.timeout: "10m"
    
    # Metrics
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: "9249"
    
  serviceAccount: flink
  
  jobManager:
    replicas: 1
    resource:
      memory: "2048"
      cpu: 1
    
  taskManager:
    resource:
      memory: "2048"
      cpu: 1
      
  job:
    jarURI: local:///opt/flink/usrlib/ping-processor.jar
    parallelism: 2
    upgradeMode: last-state
    entryClass: com.ping.PingStreamProcessor
