installCRDs: true
scylladb:
  datacenter:
    racks:
        - name: manager-rack
          storage:
            storageClassName: standard  # Use the available storage class
            capacity: 5Gi  # Adjust size as needed