apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-install
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: 1.16.0
        namespace: cert-manager
        createNamespace: true
        valuesFiles:
          - cert-manager-values.yaml
        wait: true
      - name: scylla-operator
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla-operator
        version: 1.14.0
        namespace: scylla-operator
        createNamespace: true
        wait: true
      - name: scylla-manager
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla-manager
        version: 1.14.0
        namespace: scylla-manager
        createNamespace: true
        wait: true
      - name: scylla
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla
        version: 1.14.0
        namespace: scylla
        createNamespace: true
        valuesFiles:
          - values.yaml
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=scylla"]
