apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-operator-install
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        wait: true
        setValues:
          installCRDs: true
      - name: scylla-operator
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla-operator
        namespace: scylla-operator
        createNamespace: true
        wait: true
        setValues:
          scyllaOperator:
            image:
              tag: v1.14.0
          webhookServerCert:
            certManager:
              enabled: true
            selfSigned:
              enabled: false
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=scylla-system"]
    hooks:
      after:
        - host:
            command: ["kubectl", "wait", "--for=condition=Ready", "scyllaclusters", "ping-scylla-cluster", "-n", "scylla-system", "--timeout=300s"]
manifests:
  rawYaml:
    - base/scylla-cluster.yaml
    - base/init-schema.yaml
