apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-install
deploy:
  helm:
    releases:
      - name: scylla
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla-operator
        version: 1.14.0
        namespace: scylla
        createNamespace: true
        valuesFiles:
          - values.yaml
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=scylla"]
