apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-install
deploy:
  helm:
    repositories:
      - name: jetstack
        url: https://charts.jetstack.io
    releases:
      - name: scylla
        repo: https://scylla-operator-charts.storage.googleapis.com/stable
        remoteChart: scylla-operator
        version: 1.14.0
        namespace: scylla
        createNamespace: true
        valuesFiles:
          - values.yaml
        wait: true
      - name: cert-manager
        repo: jetstack
        chart: cert-manager
        version: 1.8.0
        namespace: cert-manager
        createNamespace: true
        valuesFiles:
          - cert-manager-values.yaml
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: scylla-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=scylla"]
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: cert-manager-test
profiles:
  - name: cert-manager-test
    deploy:
      helm:
        releases:
          - name: cert-manager
            repo: jetstack
            chart: cert-manager
            version: 1.8.0
            namespace: cert-manager
            createNamespace: true
            valuesFiles:
              - cert-manager-values.yaml
            wait: true
