operator:
  image:
    tag: 1.11.1
scylla:
  clusterName: scylla-cluster
  datacenter:
    name: dc1
    racks:
      - name: rack1
        members: 3
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        storage:
          capacity: 10Gi
