apiVersion: v1
kind: Namespace
metadata:
  name: scylla-system
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: ping-scylla-cluster
  namespace: scylla-system
spec:
  version: 5.2.0
  agentVersion: 3.1.2
  repository: docker.io/scylladb/scylla
  developerMode: true
  datacenter:
    name: dc1
    racks:
      - name: rack1
        members: 1
        storage:
          capacity: 5Gi
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 4Gi
