apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dragonfly-operator-install
manifests:
  rawYaml:
    - dragonfly-operator.yaml
deploy:
  kubectl:
    flags:
      apply: [ "--namespace=dragonfly-operator-system" ]
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dragonfly-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=dragonfly-operator-system"]
manifests:
  rawYaml:
    - dragonfly.yaml
