apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: server
      ko:
        fromImage: cgr.dev/chainguard/static:latest
        platforms: ["linux/amd64"]
  local:
    useBuildkit: true
  tagPolicy:
    dateTime:
      format: "20060102.150405"
  env:
    - KO_DOCKER_REPO=ko.local
manifests:
  rawYaml:
    - server.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: server
    namespace: default
    port: 8080
    localPort: 8080
