apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: server
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - overlays/dev
portForward:
  - resourceType: service
    resourceName: server
    namespace: default
    port: 8080
    localPort: 8080
