apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: server
      ko:
        fromImage: cgr.dev/chainguard/static:latest
        labels:
          org.opencontainers.image.source: "https://github.com/wcygan/ping"
        dependencies:
          paths:
            - "**/*.go"
            - "go.mod"
            - "go.sum"
          ignore:
            - "**/testdata/**"
        ldflags:
          - "-s"
          - "-w"
  platforms: ["linux/amd64"]
  local: {}
manifests:
  rawYaml:
    - server.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: server
    namespace: default
    port: 8080
    localPort: 8080
