apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-reader
rules:
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["clusters"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list"]
