apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: pingdb
      owner: pinguser
      secret:
        name: pinguser-secret
      postInitSQL:
        - ALTER ROLE pinguser WITH LOGIN;
