apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-flink
build:
  artifacts:
  - image: ping-processor
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - base
