apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-config
build:
  artifacts:
    - image: ping-processor
      context: .
      docker:
        dockerfile: Dockerfile
      tags:
        - latest
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default"]
    hooks:
      after:
        - host:
            command: ["kubectl", "delete", "flinkdeployment", "ping-processor"]
            os: [darwin, linux]
        - host:
            command: ["sleep", "5"]
            os: [darwin, linux]
        - host:
            command: ["kubectl", "apply", "-f", "flink/base/flinkdeployment.yaml"]
            os: [darwin, linux]
manifests:
  rawYaml:
    - base/rbac.yaml
    - base/flinkdeployment.yaml
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-operator-install
deploy:
  helm:
    releases:
      - name: flink-kubernetes-operator
        repo: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.9.0
        remoteChart: flink-kubernetes-operator
        namespace: flink-operator
        createNamespace: true
        wait: true
        setValues:
          webhook.create: false
