apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-config
build:
  artifacts:
    - image: ping-processor
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_BUILDKIT: "1"
      sync:
        infer:
          - "**/*.jar"
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    useDockerCLI: true
manifests:
  rawYaml:
    - base/rbac.yaml
    - base/flinkdeployment.yaml
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default", "--force"]
    patches:
      - op: add
        path: /spec/job/upgrade/timestamp
        value: "{{.TIMESTAMP}}"
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-operator-install
deploy:
  helm:
    releases:
      - name: flink-kubernetes-operator
        repo: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.9.0
        remoteChart: flink-kubernetes-operator
        namespace: flink-operator
        createNamespace: true
        wait: true
        setValues:
          webhook.create: false
