apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-config
build:
  artifacts:
  - image: ping-processor
    jib:
      project: com.ping:ping-processor
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default"]
manifests:
  rawYaml:
    - base/rbac.yaml
    - base/flinkdeployment.yaml