apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-config
build:
  artifacts:
    - image: ping-processor-flink
      docker:
        dockerfile: flink/Dockerfile
      sync:
        manual:
          - src: "src/main/java/**/*.java"
            dest: /opt/flink/usrlib/
            strip: "src/main/java/"
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default"]
    hooks:
      after:
        - host:
            command: ["sh", "-c", "kubectl delete --wait=true flinkdeployment ping-processor || true"]
            os: [darwin, linux]
        - host:
            command: ["sh", "-c", "kubectl wait --for=delete flinkdeployment/ping-processor --timeout=60s || true"]
            os: [darwin, linux]
        - host:
            command: ["kubectl", "apply", "-f", "flink/base/flinkdeployment.yaml"]
            os: [darwin, linux]
        - host:
            command: ["kubectl", "wait", "--for=condition=Available", "flinkdeployment/ping-processor", "--timeout=120s"]
            os: [darwin, linux]
manifests:
  rawYaml:
    - base/rbac.yaml
    - base/flinkdeployment.yaml
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-operator-install
deploy:
  helm:
    releases:
      - name: flink-kubernetes-operator
        repo: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.9.0
        remoteChart: flink-kubernetes-operator
        namespace: flink-operator
        createNamespace: true
        wait: true
        setValues:
          webhook.create: false
