apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ping-flink
build:
  artifacts:
  - image: ping-processor
    jib:
      project: com.ping:ping-processor
manifests:
  rawYaml:
    - base/deployment.yaml
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default"]