apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kafka-install
deploy:
  helm:
    releases:
      - name: strimzi
        repo: https://strimzi.io/charts/
        remoteChart: strimzi-kafka-operator
        namespace: kafka-system
        createNamespace: true
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kafka-config
deploy:
  kubectl:
    flags:
      apply: ["--namespace=kafka-system"]
    hooks:
      after:
        - host:
            command: ["kubectl", "wait", "--for=condition=Ready", "kafka", "ping-kafka-cluster", "-n", "kafka-system", "--timeout=300s"]
manifests:
  rawYaml:
    - base/kafka-cluster.yaml
    - base/ping-events-topic.yaml
