apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kafka-install
deploy:
  helm:
    releases:
      - name: strimzi
        repo: https://strimzi.io/charts/
        remoteChart: strimzi-kafka-operator
        namespace: kafka-system
        createNamespace: true
        wait: true
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kafka-config
requires:
  - configs:
    - kafka-install
    path: kafka/skaffold.yaml
deploy:
  kubectl:
    flags:
      apply: ["--namespace=default"]
    manifests:
      - base/kafka-cluster.yaml
