name: Generate Go code from Buf schema

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1.45.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to buf.build
        uses: bufbuild/buf-push-action@v1.2.0
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'main'}}
          input: proto